#pragma once

#define DYNAMIC_KEYMAP_LAYER_COUNT 10
#define VIAL_KEYBOARD_UID {0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF, 0x00, 0x01}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 0 }
